version: "3"

services: 
    client-1: 
        container_name: "client-1"
        #image: auctionator:latest
        build: 
            dockerfile: ./auctionclient/Dockerfile
        environment: 
            - ID=0
            - NUMSERVERS=3
            - SERVER0=server-0:8080
            - SERVER1=server-1:8081
            - SERVER2=server-2:8082
    server-0: 
        container_name: "server-0"
        #image: auctionator:latest
        build: 
            dockerfile: ./auctionserver/Dockerfile    
        environment: 
            - PORT=8080
            - ID=0  
    server-1: 
        container_name: "server-1"
        #image: auctionator:latest
        build: 
            dockerfile: ./auctionserver/Dockerfile    
        environment: 
            - PORT=8081
            - ID=1  
    server-2: 
        container_name: "server-2"
        #image: auctionator:latest
        build: 
            dockerfile: ./auctionserver/Dockerfile    
        environment: 
            - PORT=8082
            - ID=2              