version: "3"

services: 
    client-1: 
        #overvej at sætte container-name -> husk at det skal indgå i portopsætning i programmet så! 
        image: auctionator:latest
        build: 
            dockerfile: ./auctionclient/Dockerfile
        environment: 
            #-husk at der ikke må være mellemrum!!!!
            -ID=0
            -PORT="server-1:8080"
            
    server-1: 
        #overvej container-name
        image: auctionator:latest
        build: 
            dockerfile: ./auctionserver/Dockerfile    
        environment: 
            -PORT=":8080"
            -ID=1
            -ISPRIMARY="TRUE"       
    server-2: 
        #overvej container-name
        image: auctionator:latest
        build: 
            dockerfile: ./auctionserver/Dockerfile    
        environment: 
            -PORT=":8081"
            -ID=2
            -ISPRIMARY="FALSE"
            -PRIMARY="server-1:8080"           