// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package auctionator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuctionatorClient is the client API for Auctionator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuctionatorClient interface {
	Bid(ctx context.Context, in *Amount, opts ...grpc.CallOption) (*Acknowledgement, error)
	Result(ctx context.Context, in *Uid, opts ...grpc.CallOption) (*Outcome, error)
}

type auctionatorClient struct {
	cc grpc.ClientConnInterface
}

func NewAuctionatorClient(cc grpc.ClientConnInterface) AuctionatorClient {
	return &auctionatorClient{cc}
}

func (c *auctionatorClient) Bid(ctx context.Context, in *Amount, opts ...grpc.CallOption) (*Acknowledgement, error) {
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, "/auctionator.auctionator/Bid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionatorClient) Result(ctx context.Context, in *Uid, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/auctionator.auctionator/Result", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuctionatorServer is the server API for Auctionator service.
// All implementations must embed UnimplementedAuctionatorServer
// for forward compatibility
type AuctionatorServer interface {
	Bid(context.Context, *Amount) (*Acknowledgement, error)
	Result(context.Context, *Uid) (*Outcome, error)
	mustEmbedUnimplementedAuctionatorServer()
}

// UnimplementedAuctionatorServer must be embedded to have forward compatible implementations.
type UnimplementedAuctionatorServer struct {
}

func (UnimplementedAuctionatorServer) Bid(context.Context, *Amount) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bid not implemented")
}
func (UnimplementedAuctionatorServer) Result(context.Context, *Uid) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Result not implemented")
}
func (UnimplementedAuctionatorServer) mustEmbedUnimplementedAuctionatorServer() {}

// UnsafeAuctionatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuctionatorServer will
// result in compilation errors.
type UnsafeAuctionatorServer interface {
	mustEmbedUnimplementedAuctionatorServer()
}

func RegisterAuctionatorServer(s grpc.ServiceRegistrar, srv AuctionatorServer) {
	s.RegisterService(&Auctionator_ServiceDesc, srv)
}

func _Auctionator_Bid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Amount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionatorServer).Bid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auctionator.auctionator/Bid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionatorServer).Bid(ctx, req.(*Amount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auctionator_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionatorServer).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auctionator.auctionator/Result",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionatorServer).Result(ctx, req.(*Uid))
	}
	return interceptor(ctx, in, info, handler)
}

// Auctionator_ServiceDesc is the grpc.ServiceDesc for Auctionator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auctionator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auctionator.auctionator",
	HandlerType: (*AuctionatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bid",
			Handler:    _Auctionator_Bid_Handler,
		},
		{
			MethodName: "Result",
			Handler:    _Auctionator_Result_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auctionator/auctionator.proto",
}
